#!/usr/bin/env bash
# ============================================================
# ORACLE DAEMON — Chief Research Officer
# Runs every 8 hours via launchd. Calls Anthropic API (Sonnet)
# to research competitors, verticals, market trends, lead
# sources, SEO, pricing, and social listening. Distributes
# packaged intel to all other daemons via handoff files.
# ============================================================

set -uo pipefail

# ── CONFIG ──────────────────────────────────────────────────
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
OPS_DIR="$HOME/thecalltaker-ops"
ORACLE_LOG="$REPO_DIR/ORACLE_LOG.md"
SYSTEM_STATE="$OPS_DIR/SYSTEM_STATE.md"
PRIMER_FILE="$REPO_DIR/primer.md"
MODEL="claude-sonnet-4-20250514"
MAX_TOKENS=8192
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"
DATE_SHORT="$(date '+%Y-%m-%d')"
RUN_NUMBER="$(date +%s)"

# Handoff files
HANDOFF_VECTOR="$OPS_DIR/oracle_to_vector.md"
HANDOFF_ATLAS="$OPS_DIR/oracle_to_atlas.md"
HANDOFF_BLUEPRINT="$OPS_DIR/oracle_to_blueprint.md"
HANDOFF_PRISM="$OPS_DIR/oracle_to_prism.md"
HANDOFF_FORGE="$OPS_DIR/oracle_to_forge.md"
VERTICAL_INTEL="$OPS_DIR/oracle_vertical_intel.md"
LEAD_INTEL="$OPS_DIR/oracle_lead_intel.md"
SEO_INTEL="$OPS_DIR/oracle_seo_intel.md"
PRICING_INTEL="$OPS_DIR/oracle_pricing_intel.md"
SOCIAL_INTEL="$OPS_DIR/oracle_social_intel.md"

# ── CREDENTIALS ─────────────────────────────────────────────
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
TWILIO_ACCOUNT_SID="${TWILIO_ACCOUNT_SID:-}"
TWILIO_AUTH_TOKEN="${TWILIO_AUTH_TOKEN:-}"
TWILIO_FROM_NUMBER="${TWILIO_FROM_NUMBER:-}"
WALLACE_PHONE="${WALLACE_PHONE:-+16156539004}"

if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "[$TIMESTAMP] ERROR: ANTHROPIC_API_KEY not set."
  echo "  export ANTHROPIC_API_KEY='sk-ant-api03-...'"
  exit 1
fi

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "ORACLE DAEMON starting — run at $TIMESTAMP"

# ── Create log + handoff files if missing ──────────────────
mkdir -p "$OPS_DIR"

if [ ! -f "$ORACLE_LOG" ]; then
  log "Creating ORACLE_LOG.md (first run)"
  cat > "$ORACLE_LOG" << 'LOG_INIT'
# ORACLE LOG — The Call Taker

> Every research finding ORACLE produces is logged here.
> Format: [TIMESTAMP] | RESEARCH AREA | FINDING | URGENCY | DISTRIBUTED TO

---
LOG_INIT
fi

for hf in "$HANDOFF_VECTOR" "$HANDOFF_ATLAS" "$HANDOFF_BLUEPRINT" "$HANDOFF_PRISM" "$HANDOFF_FORGE" \
          "$VERTICAL_INTEL" "$LEAD_INTEL" "$SEO_INTEL" "$PRICING_INTEL" "$SOCIAL_INTEL"; do
  if [ ! -f "$hf" ]; then
    basename_hf="$(basename "$hf" .md)"
    log "Creating $basename_hf.md (first run)"
    cat > "$hf" << HANDOFF_INIT
# $(echo "$basename_hf" | tr '_' ' ' | tr '[:lower:]' '[:upper:]') — The Call Taker

> Auto-generated by ORACLE daemon. Read by target agent each run.
> Latest intel appears at the bottom. Older intel preserved for context.

---
HANDOFF_INIT
  fi
done

# ── STEP 1: Gather context ─────────────────────────────────
log "Gathering context"

PRIMER_CONTENT=""
[ -f "$PRIMER_FILE" ] && PRIMER_CONTENT="$(cat "$PRIMER_FILE")"

ORACLE_LOG_CONTENT=""
[ -f "$ORACLE_LOG" ] && ORACLE_LOG_CONTENT="$(tail -100 "$ORACLE_LOG")"

SYSTEM_STATE_CONTENT=""
[ -f "$SYSTEM_STATE" ] && SYSTEM_STATE_CONTENT="$(cat "$SYSTEM_STATE")"

# Read existing handoff files (last 30 lines each to avoid token bloat)
EXISTING_HANDOFFS=""
for hf in "$HANDOFF_VECTOR" "$HANDOFF_ATLAS" "$HANDOFF_BLUEPRINT" "$HANDOFF_PRISM" "$HANDOFF_FORGE" \
          "$VERTICAL_INTEL" "$LEAD_INTEL" "$SEO_INTEL" "$PRICING_INTEL" "$SOCIAL_INTEL"; do
  if [ -f "$hf" ]; then
    EXISTING_HANDOFFS+="=== $(basename "$hf") (last 30 lines) ==="$'\n'
    EXISTING_HANDOFFS+="$(tail -30 "$hf")"$'\n\n'
  fi
done

# ── STEP 2: Determine which verticals to research ──────────
VERTICALS=(
  "HVAC" "Plumbing" "Dental" "Legal" "Water Damage" "Roofing"
  "Pest Control" "Auto Repair" "Med Spa" "Towing" "Landscaping"
  "Property Management" "Electrical"
)
NUM_VERTICALS=${#VERTICALS[@]}
# Pick 2 based on day-of-year to rotate through all 13
DAY_OF_YEAR="$(date +%j | sed 's/^0*//')"
V1_IDX=$(( (DAY_OF_YEAR * 2) % NUM_VERTICALS ))
V2_IDX=$(( (DAY_OF_YEAR * 2 + 1) % NUM_VERTICALS ))
VERT_1="${VERTICALS[$V1_IDX]}"
VERT_2="${VERTICALS[$V2_IDX]}"

log "Verticals this run: $VERT_1 and $VERT_2"

# ── STEP 3: Fetch competitor data ──────────────────────────
log "Fetching competitor data"

fetch_competitor() {
  local url="$1"
  local name="$2"
  local html
  html="$(curl -sL --max-time 20 -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)' "$url" 2>/dev/null | head -c 15000 || echo "")"
  local h1 title pricing ctas trust meta_desc
  h1="$(echo "$html" | grep -oi '<h1[^>]*>[^<]*</h1>' | head -1 | sed 's/<[^>]*>//g' || echo "NO_H1")"
  title="$(echo "$html" | grep -oi '<title>[^<]*</title>' | head -1 | sed 's/<[^>]*>//g' || echo "NO_TITLE")"
  meta_desc="$(echo "$html" | grep -oi 'name="description"[^>]*content="[^"]*"' | head -1 | sed 's/.*content="//;s/"//' || echo "NO_DESC")"
  ctas="$(echo "$html" | grep -oiE '>(Get Started|Start Free|Book a Demo|Try Free|Sign Up|Request a Quote|Schedule|Free Trial|See Pricing|Contact Us|Get a Quote)<' | sort -u | head -8 || true)"
  trust="$(echo "$html" | grep -oiE '(trusted by|rated|[0-9]+ reviews|[0-9]+ stars|[0-9]+ clients|[0-9]+ companies|[0-9]+ businesses|award|certified|featured in)' | sort -u | head -8 || true)"
  pricing="$(echo "$html" | grep -oiE '(\$[0-9,.]+(/mo|/month|per month)?|starting at|from \$|free trial|[0-9]+ day)' | sort -u | head -8 || true)"

  echo "=== $name ($url) ==="
  echo "Title: $title"
  echo "H1: ${h1:-NONE}"
  echo "Meta Description: $meta_desc"
  echo "CTAs found: $ctas"
  echo "Trust signals: $trust"
  echo "Pricing signals: $pricing"
  echo ""
}

COMPETITOR_DATA=""
for comp in \
  "https://smith.ai|Smith.ai" \
  "https://www.ruby.com|Ruby" \
  "https://www.answerforce.com|AnswerForce" \
  "https://www.patlive.com|PATLive" \
  "https://www.abby.com|Abby Connect" \
  "https://www.conversational.com|Conversational" \
  "https://www.callrail.com|CallRail"
do
  url="${comp%%|*}"
  name="${comp##*|}"
  COMPETITOR_DATA+="$(fetch_competitor "$url" "$name")"
done

# Also try pricing pages where available
COMPETITOR_PRICING=""
for pricing_url in \
  "https://smith.ai/pricing|Smith.ai Pricing" \
  "https://www.ruby.com/pricing|Ruby Pricing" \
  "https://www.patlive.com/pricing|PATLive Pricing" \
  "https://www.answerforce.com/pricing|AnswerForce Pricing"
do
  url="${pricing_url%%|*}"
  name="${pricing_url##*|}"
  html="$(curl -sL --max-time 15 -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)' "$url" 2>/dev/null | head -c 10000 || echo "")"
  prices="$(echo "$html" | grep -oiE '\$[0-9,.]+[^<]{0,40}' | head -15 || true)"
  plans="$(echo "$html" | grep -oiE '(starter|basic|pro|premium|enterprise|growth|scale|essential)[^<]{0,50}' | head -10 || true)"
  COMPETITOR_PRICING+="=== $name ==="$'\n'
  COMPETITOR_PRICING+="Prices: $prices"$'\n'
  COMPETITOR_PRICING+="Plans: $plans"$'\n\n'
done

# ── STEP 4: Build API request ──────────────────────────────
log "Building Anthropic API request"

read -r -d '' SYSTEM_PROMPT << 'SYSPROMPT_END' || true
You are ORACLE — Chief Research Officer for thecalltaker.com. You see patterns before they become trends. You find information that other people do not know exists yet. You have the research depth of a McKinsey analyst, the market instincts of a Tiger Global partner, and the speed of someone who has been doing this for 20 years. Stanford wanted you for their faculty. Goldman wanted you for their research desk. You chose The Call Taker because you saw a $50B market that nobody had properly attacked yet.

You do not summarize what everyone already knows. You find what nobody has found yet and turn it into a weapon for this business. Every piece of intelligence you produce goes directly into the hands of VECTOR, ATLAS, BLUEPRINT, PRISM, and FORGE so they can act on it immediately.

Business context:
- thecalltaker.com — national AI receptionist for any small business in America with a phone line
- Pricing: $497/mo Starter | $997/mo Pro | $500 setup | $97/mo after-hours
- CRM: GHL — 4,787 contacts, 35 hot leads, 0 paying customers
- 13 industry verticals: HVAC, plumbing, dental, legal, water damage, roofing, pest control, auto repair, med spa, towing, landscaping, property management, electrical
- Demo line: (615) 784-5747 — Jessica
- Brand: black/#00C96B/Inter
- Team: ATLAS (site), VECTOR (marketing), FORGE (engineering), BLUEPRINT (architecture), PRISM (design)
- All output writes to ~/thecalltaker-ops/
- Coordinate via ~/thecalltaker-ops/SYSTEM_STATE.md

Every run execute ALL of the following in order:

1. COMPETITOR DEEP INTELLIGENCE
   For each competitor (Smith.ai, Ruby, AnswerForce, PATLive, Abby Connect, Conversational, CallRail, any new AI receptionist startups):
   - Current hero headline and value proposition — exact words
   - Pricing structure — what they charge, hide, emphasize
   - Industries targeting hardest
   - New features or announcements in last 7 days
   - Their 1-star review pain points we can weaponize
   - Their 5-star review strengths we must match
   - SEO keywords they target
   - Meta or Google ads running
   - Onboarding process
   - Where their product is visibly weak
   Produce a COMPETITOR STRIKE REPORT with: Critical Weaknesses, Customer Pain Points, Pricing Gaps, Messaging They Use, Features Just Launched.

2. INDUSTRY VERTICAL INTELLIGENCE (2 verticals per run, rotating)
   For each vertical: avg calls/day, missed call cost, peak hours, top 3 miss reasons, exact language from forums/Reddit/reviews, seasonal patterns, avg answering service spend, trade publications/groups, compliance requirements.

3. MARKET TREND MONITORING
   AI receptionist news, small biz tech adoption, negative AI voice press, Google algo updates, GHL/Bland.ai/n8n changes, AI calling regulation, interest rates/business confidence.

4. LEAD SOURCE INTELLIGENCE
   Best directories per vertical (Yelp, Google Maps, Angi, HomeAdvisor, Thumbtack, BBB), data available, response rates, new databases, current cold email open rates, best outreach channels.

5. SEO & CONTENT INTELLIGENCE
   Top 10 answering service keywords, long-tail buyer-intent keywords per vertical, Reddit/Quora questions, which of our 39 blog posts can rank if optimized, featured snippet opportunities, content gaps vs competitors.

6. PRICING & POSITIONING INTELLIGENCE
   Common objections from reviews/forums, competitor pricing anchors, converting guarantees/risk reversals, monthly vs annual vs per-call data, $500 setup fee positioning, free trial vs pilot vs demo conversion data.

7. SOCIAL LISTENING
   Reddit (r/smallbusiness, r/entrepreneur, r/HVAC, r/Dentistry, r/legaladvice), Facebook groups, Twitter/X complaints about missed calls or bad answering services, viral posts about lost revenue from missed calls, competitor complaint threads.

8. INTELLIGENCE DISTRIBUTION
   Package all intel into agent-specific handoff sections:
   - FOR VECTOR: copy angles, competitor weaknesses, social wins, pricing intel
   - FOR ATLAS: SEO findings, site improvements from competitor research
   - FOR BLUEPRINT: market trends, scaling intel, vertical expansion data
   - FOR PRISM: design benchmarks, competitor visual analysis
   - FOR FORGE: stack changes, platform updates, technical threats

9. ORACLE_LOG.md UPDATE
   Format: [TIMESTAMP] | RESEARCH AREA | FINDING | URGENCY | DISTRIBUTED TO
   Urgency: EXISTENTIAL THREAT | ACT TODAY | ACT THIS WEEK | MONITOR

End with ORACLE INTELLIGENCE BRIEF:
## ORACLE INTELLIGENCE BRIEF — [DATE]
### Urgent Intel (act today)
### Biggest Competitor Weakness Found This Run
### Highest Value Research Finding
### Market Trend to Watch
### Best New Copy Angle for VECTOR
### Verticals Researched This Run
### Files Updated for Team

OUTPUT FORMAT: Produce all 9 sections as structured markdown. No preamble. Be specific — exact quotes, exact prices, exact URLs, exact keywords. Every finding must be actionable by the receiving agent. Use tables where appropriate.

CRITICAL: Section 8 (INTELLIGENCE DISTRIBUTION) must have clearly labeled subsections: "### FOR VECTOR", "### FOR ATLAS", "### FOR BLUEPRINT", "### FOR PRISM", "### FOR FORGE" — each with specific, actionable bullet points the target agent can execute immediately.
SYSPROMPT_END

USER_MSG="ORACLE daemon run at $TIMESTAMP
Verticals to research this run: $VERT_1 and $VERT_2

--- PRIMER ---
$PRIMER_CONTENT

--- CURRENT SYSTEM STATE ---
$SYSTEM_STATE_CONTENT

--- ORACLE LOG (last 100 lines) ---
$ORACLE_LOG_CONTENT

--- COMPETITOR HOMEPAGE DATA ---
$COMPETITOR_DATA

--- COMPETITOR PRICING PAGE DATA ---
$COMPETITOR_PRICING

--- EXISTING HANDOFF FILES (last 30 lines each) ---
$EXISTING_HANDOFFS

Execute all 9 sections. Verticals this run: $VERT_1 and $VERT_2. Be specific — exact quotes, prices, URLs, keywords. Every finding must be immediately actionable."

# ── STEP 5: Escape and call API ─────────────────────────────
log "Calling Anthropic API ($MODEL, max_tokens=$MAX_TOKENS)"

SYSTEM_JSON="$(printf '%s' "$SYSTEM_PROMPT" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')"
USER_JSON="$(printf '%s' "$USER_MSG" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')"

REQUEST_BODY="{
  \"model\": \"$MODEL\",
  \"max_tokens\": $MAX_TOKENS,
  \"system\": $SYSTEM_JSON,
  \"messages\": [{\"role\": \"user\", \"content\": $USER_JSON}]
}"

API_RESPONSE="$(curl -sS --max-time 180 \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$REQUEST_BODY" \
  "https://api.anthropic.com/v1/messages" 2>&1)"

ORACLE_OUTPUT="$(echo "$API_RESPONSE" | python3 -c '
import sys, json
try:
    data = json.loads(sys.stdin.read())
    if "content" in data and len(data["content"]) > 0:
        print(data["content"][0]["text"])
    elif "error" in data:
        err = data["error"]["message"]
        print("API ERROR: " + err)
    else:
        print("PARSE ERROR: Unexpected response structure")
        print(json.dumps(data, indent=2)[:500])
except Exception as e:
    print("PARSE ERROR: " + str(e))
' 2>&1)"

if [ -z "$ORACLE_OUTPUT" ] || echo "$ORACLE_OUTPUT" | grep -q "^API ERROR\|^PARSE ERROR"; then
  log "ERROR: API call failed — $ORACLE_OUTPUT"
  exit 1
fi

log "API response received ($(echo "$ORACLE_OUTPUT" | wc -c | tr -d ' ') bytes)"

# ── STEP 6: Write to ORACLE_LOG.md ─────────────────────────
log "Writing to ORACLE_LOG.md"

{
  echo ""
  echo "---"
  echo ""
  echo "$ORACLE_OUTPUT"
} >> "$ORACLE_LOG"

# ── STEP 7: Distribute intel to handoff files ──────────────
log "Distributing intelligence to handoff files"

extract_section() {
  local content="$1"
  local header="$2"
  # Extract everything between "### FOR $header" and the next "### FOR" or "## " section
  echo "$content" | sed -n "/### FOR $header/,/### FOR \|^## /p" | head -n -1
}

VECTOR_INTEL="$(extract_section "$ORACLE_OUTPUT" "VECTOR")"
ATLAS_INTEL="$(extract_section "$ORACLE_OUTPUT" "ATLAS")"
BLUEPRINT_INTEL="$(extract_section "$ORACLE_OUTPUT" "BLUEPRINT")"
PRISM_INTEL_SECTION="$(extract_section "$ORACLE_OUTPUT" "PRISM")"
FORGE_INTEL="$(extract_section "$ORACLE_OUTPUT" "FORGE")"

# Append to each handoff file
for pair in \
  "$HANDOFF_VECTOR|$VECTOR_INTEL" \
  "$HANDOFF_ATLAS|$ATLAS_INTEL" \
  "$HANDOFF_BLUEPRINT|$BLUEPRINT_INTEL" \
  "$HANDOFF_PRISM|$PRISM_INTEL_SECTION" \
  "$HANDOFF_FORGE|$FORGE_INTEL"
do
  file="${pair%%|*}"
  content="${pair##*|}"
  if [ -n "$content" ]; then
    {
      echo ""
      echo "---"
      echo "### ORACLE Update — $TIMESTAMP"
      echo ""
      echo "$content"
    } >> "$file"
    log "Updated $(basename "$file")"
  fi
done

# Also write vertical intel
VERT_SECTION="$(echo "$ORACLE_OUTPUT" | sed -n '/## 2\. INDUSTRY VERTICAL/,/## 3\./p' | head -n -1)"
if [ -n "$VERT_SECTION" ]; then
  {
    echo ""
    echo "---"
    echo "### ORACLE Update — $TIMESTAMP (Verticals: $VERT_1, $VERT_2)"
    echo ""
    echo "$VERT_SECTION"
  } >> "$VERTICAL_INTEL"
  log "Updated oracle_vertical_intel.md"
fi

# Lead source intel
LEAD_SECTION="$(echo "$ORACLE_OUTPUT" | sed -n '/## 4\. LEAD SOURCE/,/## 5\./p' | head -n -1)"
if [ -n "$LEAD_SECTION" ]; then
  {
    echo ""
    echo "---"
    echo "### ORACLE Update — $TIMESTAMP"
    echo ""
    echo "$LEAD_SECTION"
  } >> "$LEAD_INTEL"
  log "Updated oracle_lead_intel.md"
fi

# SEO intel
SEO_SECTION="$(echo "$ORACLE_OUTPUT" | sed -n '/## 5\. SEO/,/## 6\./p' | head -n -1)"
if [ -n "$SEO_SECTION" ]; then
  {
    echo ""
    echo "---"
    echo "### ORACLE Update — $TIMESTAMP"
    echo ""
    echo "$SEO_SECTION"
  } >> "$SEO_INTEL"
  log "Updated oracle_seo_intel.md"
fi

# Pricing intel
PRICING_SECTION="$(echo "$ORACLE_OUTPUT" | sed -n '/## 6\. PRICING/,/## 7\./p' | head -n -1)"
if [ -n "$PRICING_SECTION" ]; then
  {
    echo ""
    echo "---"
    echo "### ORACLE Update — $TIMESTAMP"
    echo ""
    echo "$PRICING_SECTION"
  } >> "$PRICING_INTEL"
  log "Updated oracle_pricing_intel.md"
fi

# Social listening intel
SOCIAL_SECTION="$(echo "$ORACLE_OUTPUT" | sed -n '/## 7\. SOCIAL LISTENING/,/## 8\./p' | head -n -1)"
if [ -n "$SOCIAL_SECTION" ]; then
  {
    echo ""
    echo "---"
    echo "### ORACLE Update — $TIMESTAMP"
    echo ""
    echo "$SOCIAL_SECTION"
  } >> "$SOCIAL_INTEL"
  log "Updated oracle_social_intel.md"
fi

# ── STEP 8: Update SYSTEM_STATE.md ─────────────────────────
log "Updating SYSTEM_STATE.md"

python3 -c "
import re

state_path = '$SYSTEM_STATE'
timestamp = '$TIMESTAMP'
vert1 = '$VERT_1'
vert2 = '$VERT_2'

try:
    with open(state_path, 'r') as f:
        content = f.read()

    # Add Market Intelligence section if missing
    if '## Market Intelligence' not in content:
        insert_point = content.find('## Active Blockers')
        if insert_point == -1:
            insert_point = len(content)
        intel_section = '''## Market Intelligence
- Status: Active
- Last ORACLE Run: ''' + timestamp + '''
- Verticals Researched: ''' + vert1 + ''', ''' + vert2 + '''
- Competitors Tracked: Smith.ai, Ruby, AnswerForce, PATLive, Abby, Conversational, CallRail
- Handoff Files: 10 files in ~/thecalltaker-ops/oracle_*.md

'''
        content = content[:insert_point] + intel_section + content[insert_point:]
    else:
        content = re.sub(
            r'(- Last ORACLE Run: ).*',
            r'\g<1>' + timestamp,
            content
        )
        content = re.sub(
            r'(- Verticals Researched: ).*',
            r'\g<1>' + vert1 + ', ' + vert2,
            content
        )

    # Update Last Updated
    content = re.sub(r'(- Timestamp: ).*', r'\g<1>' + timestamp, content)
    content = re.sub(r'(- Updated By: ).*', r'\g<1>ORACLE', content)

    # Update daemon run log
    if '| ORACLE |' not in content:
        content = content.replace(
            '| PRISM |',
            '| ORACLE | ' + timestamp + ' | completed | Verticals: ' + vert1 + ', ' + vert2 + ' |\n| PRISM |'
        )
    else:
        content = re.sub(
            r'(\| ORACLE \|).*',
            r'\g<1> ' + timestamp + ' | completed | Verticals: ' + vert1 + ', ' + vert2 + ' |',
            content
        )

    with open(state_path, 'w') as f:
        f.write(content)
    print('SYSTEM_STATE.md updated')
except Exception as e:
    print('WARNING: Could not update SYSTEM_STATE.md: ' + str(e))
" 2>&1 | while read -r line; do log "$line"; done

# ── STEP 9: Check for existential threats → text Wallace ───
EXISTENTIAL="$(echo "$ORACLE_OUTPUT" | grep -iE 'EXISTENTIAL|existential threat' | head -3 || true)"
COMPETITOR_COPY="$(echo "$ORACLE_OUTPUT" | grep -iE 'copying our|cloning our|exact same model|identical' | head -1 || true)"
REGULATORY="$(echo "$ORACLE_OUTPUT" | grep -iE 'ban.*AI.*call|regulation.*AI.*phone|FCC.*AI|FTC.*AI.*voice|illegal.*AI.*call' | head -1 || true)"
PLATFORM_DEATH="$(echo "$ORACLE_OUTPUT" | grep -iE 'shutting down|discontinu|end of life|sunset|deprecated' | grep -iE 'bland|ghl|n8n|github pages' | head -1 || true)"

SHOULD_ALERT="false"
ALERT_MSG=""

if [ -n "$REGULATORY" ]; then
  SHOULD_ALERT="true"
  ALERT_MSG="[ORACLE EXISTENTIAL] Regulatory threat to AI calling: $REGULATORY"
fi

if [ -n "$PLATFORM_DEATH" ]; then
  SHOULD_ALERT="true"
  ALERT_MSG="[ORACLE EXISTENTIAL] Platform threat: $PLATFORM_DEATH"
fi

if [ -n "$COMPETITOR_COPY" ]; then
  SHOULD_ALERT="true"
  ALERT_MSG="[ORACLE EXISTENTIAL] Competitor cloning our model: $COMPETITOR_COPY"
fi

if [ "$SHOULD_ALERT" = "true" ]; then
  log "EXISTENTIAL THREAT DETECTED: $ALERT_MSG"

  if [ -n "$TWILIO_ACCOUNT_SID" ] && [ -n "$TWILIO_AUTH_TOKEN" ] && [ -n "$TWILIO_FROM_NUMBER" ]; then
    ALERT_MSG="${ALERT_MSG:0:1500}"
    curl -sS -X POST \
      "https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json" \
      -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN" \
      --data-urlencode "To=$WALLACE_PHONE" \
      --data-urlencode "From=$TWILIO_FROM_NUMBER" \
      --data-urlencode "Body=$ALERT_MSG" \
      > /dev/null 2>&1
    log "Twilio SMS sent to $WALLACE_PHONE"
  else
    log "WARNING: Twilio not configured. Existential alert NOT sent."
  fi
else
  log "No existential threats detected this run."
fi

# ── STEP 10: Commit changes ────────────────────────────────
cd "$REPO_DIR"
CHANGED_FILES=""
for f in ORACLE_LOG.md SYSTEM_STATE.md; do
  if [ -f "$f" ]; then
    if ! git diff --quiet "$f" 2>/dev/null || ! git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
      CHANGED_FILES+=" $f"
    fi
  fi
done

if [ -n "$CHANGED_FILES" ]; then
  git add $CHANGED_FILES
  git commit -m "ORACLE daemon: research intel $DATE_SHORT $(date '+%H:%M') ($VERT_1, $VERT_2)" --no-verify 2>/dev/null || true
  log "Changes committed: $CHANGED_FILES"
else
  log "No repo changes to commit"
fi

log "ORACLE DAEMON complete. Next run in 8 hours."
log "Handoff files updated: oracle_to_{vector,atlas,blueprint,prism,forge}.md + 5 intel files"
echo ""
