"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const setup = fs.readFileSync(path.join(root, "website/setup.html"), "utf8");
const confirmation = fs.readFileSync(path.join(root, "website/setup-confirmation.html"), "utf8");
const workflow = fs.readFileSync(path.join(root, ".github/workflows/deploy.yml"), "utf8");
assert.equal(setup.includes("<form"), false, "unsigned public setup cannot collect onboarding data");
assert.equal(confirmation.includes("questions were received"), false, "direct confirmation cannot claim a receipt");
assert.match(setup, /Nothing was activated/);
assert.match(confirmation, /not a payment or setup receipt/);
assert.equal(workflow.includes("setup-form.js"), false, "retired setup form code is not deployed");
console.log("retired public setup route tests passed");
