"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const routeFiles = ["index.html","pricing.html","demo.html","meet-gideon.html","book.html","card-checkout.html","setup.html","setup-confirmation.html"];
const release = routeFiles.map((file) => read(`website/${file}`)).join("\n");
assert.doesNotMatch(release, /setupToken|tct_setup_binding|trial=started|receipt=/);
assert.doesNotMatch(release, /thecalltaker\.vercel\.app/);
assert.match(read("website/book.html"), /consented-demo-lead/);
assert.match(read("website/demo.html"), /explicit follow-up consent|required/);
assert.match(read("website/card-checkout.html"), /payment pending|payment_pending/i);
assert.match(read("website/setup.html"), /public setup form is retired/i);
console.log("website release candidate tests passed");
