"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..", "..");
const entrypoint = fs.readFileSync(path.join(root, "website/tct-tracking.js"), "utf8");
const canonical = fs.readFileSync(path.join(root, "website/tct-funnel-events.js"), "utf8");
assert.match(entrypoint, /Canonical public attribution entrypoint/);
assert.match(entrypoint, /TCT_ATTRIBUTION_ENTRYPOINT_VERSION = "tct-tracking-entrypoint-v1"/);
assert.match(entrypoint, /tct-funnel-events\.js/);
assert.match(entrypoint, /__TCT_ATTRIBUTION_ENTRYPOINT_LOADED__/);
assert.match(canonical, /api\/public\/buyer-event/);
assert.match(canonical, /credentials:\s*"omit"/);
assert.match(canonical, /2129562004253413/);
assert.doesNotMatch(canonical, /XXXXXXXXXX/);
assert.match(canonical, /__TCT_FUNNEL_EVENTS_INITIALIZED__/);
console.log("privacy-safe conversion tracking release tests passed");
