"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..", "..");
const legacy = fs.readFileSync(path.join(root, "website/tct-tracking.js"), "utf8");
const canonical = fs.readFileSync(path.join(root, "website/tct-funnel-events.js"), "utf8");
assert.match(legacy, /TCTLeadCapture/);
assert.match(legacy, /return false/);
assert.doesNotMatch(legacy, /fetch\(|fbq|gtag|email|phone|popup/i);
assert.match(canonical, /api\/public\/buyer-event/);
assert.match(canonical, /credentials:\s*"omit"/);
console.log("privacy-safe conversion tracking release tests passed");
